In [1]:
import numpy as np
import tensorflow as tf

n_examples = 10
n_features = 10

In [3]:
examples = np.random.randint(0, 100, size = (n_examples, n_features))
examples

array([[98, 89, 81, 31, 13, 17, 86, 11, 99, 72],
       [60, 35, 83, 45, 11, 75, 45, 65, 34, 52],
       [39, 76, 96, 85, 20, 91, 34, 35, 15, 29],
       [70, 75, 39, 71, 55, 71, 22, 84, 89, 43],
       [70,  7, 72,  3, 68, 42, 16, 28, 20, 85],
       [40, 78,  6, 36, 47, 21, 82,  7, 35, 58],
       [84, 31, 87, 98, 95,  5, 82, 35, 58, 10],
       [86, 65, 54, 13, 41, 55, 24, 75, 21, 42],
       [57, 29, 69, 84, 63, 61, 28, 14,  1, 90],
       [76, 80, 24, 61, 19, 91, 17, 23, 29, 86]])

In [5]:
for idx in range(examples.shape[0]):
    print("label={}, feature={}".format(idx, examples[idx]))

label=0, feature=[98 89 81 31 13 17 86 11 99 72]
label=1, feature=[60 35 83 45 11 75 45 65 34 52]
label=2, feature=[39 76 96 85 20 91 34 35 15 29]
label=3, feature=[70 75 39 71 55 71 22 84 89 43]
label=4, feature=[70  7 72  3 68 42 16 28 20 85]
label=5, feature=[40 78  6 36 47 21 82  7 35 58]
label=6, feature=[84 31 87 98 95  5 82 35 58 10]
label=7, feature=[86 65 54 13 41 55 24 75 21 42]
label=8, feature=[57 29 69 84 63 61 28 14  1 90]
label=9, feature=[76 80 24 61 19 91 17 23 29 86]


In [8]:
with tf.io.TFRecordWriter('example.tfrecord') as tfrecord:
    for idx in range(examples.shape[0]):
        label = [idx]
        feature = examples[idx]
        features = {
            'label': tf.train.Feature(int64_list = tf.train.Int64List(value = label)),
            'feature': tf.train.Feature(int64_list = tf.train.Int64List(value = feature))
        }
        example = tf.train.Example(features = tf.train.Features(feature = features))
        tfrecord.write(example.SerializeToString())

In [10]:
def map_fn(serialized_example):
    feature = {
        'label': tf.io.FixedLenFeature([1], tf.int64),
        'feature': tf.io.FixedLenFeature([n_features], tf.int64)
    }
    example = tf.io.parse_single_example(serialized_example, feature)
    return example['feature'], example['label']

In [11]:
dataset = tf.data.TFRecordDataset('example.tfrecord')
dataset = dataset.map(map_fn)

Metal device set to: Apple M1 Pro


2022-11-03 20:47:02.592545: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-11-03 20:47:02.593417: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [22]:
for feature, label in dataset.take(10):
    print(feature)

tf.Tensor([98 89 81 31 13 17 86 11 99 72], shape=(10,), dtype=int64)
tf.Tensor([60 35 83 45 11 75 45 65 34 52], shape=(10,), dtype=int64)
tf.Tensor([39 76 96 85 20 91 34 35 15 29], shape=(10,), dtype=int64)
tf.Tensor([70 75 39 71 55 71 22 84 89 43], shape=(10,), dtype=int64)
tf.Tensor([70  7 72  3 68 42 16 28 20 85], shape=(10,), dtype=int64)
tf.Tensor([40 78  6 36 47 21 82  7 35 58], shape=(10,), dtype=int64)
tf.Tensor([84 31 87 98 95  5 82 35 58 10], shape=(10,), dtype=int64)
tf.Tensor([86 65 54 13 41 55 24 75 21 42], shape=(10,), dtype=int64)
tf.Tensor([57 29 69 84 63 61 28 14  1 90], shape=(10,), dtype=int64)
tf.Tensor([76 80 24 61 19 91 17 23 29 86], shape=(10,), dtype=int64)


In [23]:
data1 = dataset.take(1)

In [40]:
print(data1.as_numpy_iterator())
print(list(data1.as_numpy_iterator()))
print(list(data1.as_numpy_iterator())[0])
print(list(data1.as_numpy_iterator())[0][0])
print(list(list(data1.as_numpy_iterator())[0][0]))
print([list(list(data1.as_numpy_iterator())[0][0])])

[(array([98, 89, 81, 31, 13, 17, 86, 11, 99, 72]), array([0]))]
(array([98, 89, 81, 31, 13, 17, 86, 11, 99, 72]), array([0]))
[98 89 81 31 13 17 86 11 99 72]
[98, 89, 81, 31, 13, 17, 86, 11, 99, 72]
[[98, 89, 81, 31, 13, 17, 86, 11, 99, 72]]
